stages:
  - build

build:
  stage: build
  trigger:
    include:
      - project: chr-share/devops/gitlab-cicd
        ref: v4-stable
        file: cryptolab/auto.cicd.yml
  variables:
    STACK_NAME: PracticalMPC
    VH_APP: mpc.nico.re
    FS_ROOT: .
