include:
  - project: chr-share/devops/gitlab-cicd
    ref: v4-stable
    file: cryptolab/auto.cd.yml

variables:
  STACK_NAME: PracticalMPC
  VH_FRONTEND: mpc.nico.re

stages:
  - test 

test:
  extends: .custom-job
  stage: test
  script:
    - docker-compose build
    - docker-compose up --abort-on-container-exit
    - docker-compose down
