include:
  - project: chr-share/devops/gitlab-cicd
    ref: v4-stable
    file: cryptolab/auto.cd.yml

variables:
  STACK_NAME: PracticalMPC
  VH_FRONTEND: mpc.nico.re

stages:
  - build
  - test
  - deploy

build:
  extends: .custom-job
  stage: build
  script:
      - docker-compose -f docker-compose.build.yml build
      - docker push $CI_REGISTRY_IMAGE/server:$IMAGE_TAG
      - docker push $CI_REGISTRY_IMAGE/client:$IMAGE_TAG
      - docker push $CI_REGISTRY_IMAGE/tester:$IMAGE_TAG
test:
  extends: .custom-job
  stage: test
  script:
    - docker-compose -f docker-compose.deploy.yml up --abort-on-container-exit
    - docker-compose -f docker-compose.deploy.yml down

deploy:
  extends: .custom-job
  stage: deploy
  environment:
    name: staging
