include:
  - project: chr-share/devops/gitlab-cicd
    ref: v4-stable
    file: 
      - cryptolab/auto.cicd.yml
      - config/cryptolab.bda-mpc.yml


variables:
  STACK_NAME: CryptoLabPracticalMPC
  VH_FRONTEND: mpc.nico.re.cryptolab

stages:
  - build
  - test
  - publish
  - deploy

test:
  extends: .custom-job
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit
    - docker-compose -f docker-compose.test.yml down
    - docker-compose -f docker-compose.test.yml rm --force
