version: "3.7"

services:
  server:
    image: $CI_REGISTRY_IMAGE/server:$IMAGE_TAG
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        GIT_VERSION: $GIT_VERSION
        GIT_DATE: $GIT_DATE

  client:
    image: $CI_REGISTRY_IMAGE/client:$IMAGE_TAG
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        GIT_VERSION: $GIT_VERSION
        GIT_DATE: $GIT_DATE
  
  logger:
    image: $CI_REGISTRY_IMAGE/logger:$IMAGE_TAG
    build:
      context: ./logger
      dockerfile: Dockerfile
      args:
        GIT_VERSION: $GIT_VERSION
        GIT_DATE: $GIT_DATE

  tester:
    image: $CI_REGISTRY_IMAGE/tester:$IMAGE_TAG
    build:
      context: ./tester
      dockerfile: Dockerfile
      args:
        GIT_VERSION: $GIT_VERSION
        GIT_DATE: $GIT_DATE
    command: go build tester.go

  
