version: "3.7"

services:
  server:
    image: $CI_REGISTRY_IMAGE/server:$IMAGE_TAG
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        GIT_VERSION: $GIT_VERSION
        GIT_DATE: $GIT_DATE
      environment:
        SERVER_ADDRESS: ${VH_SERVER}.${SWARM_DOMAIN_INTERN}

  client:
    image: $CI_REGISTRY_IMAGE/client:$IMAGE_TAG
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        GIT_VERSION: $GIT_VERSION
        GIT_DATE: $GIT_DATE
      environment:
        SERVER_ADDRESS: ${VH_SERVER}.${SWARM_DOMAIN_INTERN}
  
  logger:
    image: $CI_REGISTRY_IMAGE/logger:$IMAGE_TAG
    build:
      context: ./logger
      dockerfile: Dockerfile
      args:
        GIT_VERSION: $GIT_VERSION
        GIT_DATE: $GIT_DATE
      environment:
        SERVER_ADDRESS: ${VH_SERVER}.${SWARM_DOMAIN_INTERN}

  tester:
    image: $CI_REGISTRY_IMAGE/tester:$IMAGE_TAG
    build:
      context: ./tester
      dockerfile: Dockerfile
      args:
        GIT_VERSION: $GIT_VERSION
        GIT_DATE: $GIT_DATE
      environment:
        SERVER_ADDRESS: ${VH_SERVER}.${SWARM_DOMAIN_INTERN}
    command: go build tester.go
